// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import TeamOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/TeamOutlined';
import UserAddOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/UserAddOutlined';
import SoundOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/SoundOutlined';
import DollarOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/DollarOutlined';
import CheckSquareOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/CheckSquareOutlined';
import SettingOutlined from '/Users/kun_mac/Desktop/Project/vend_admin/node_modules/@ant-design/icons/es/icons/SettingOutlined';
export default { SmileOutlined, TeamOutlined, UserAddOutlined, SoundOutlined, DollarOutlined, CheckSquareOutlined, SettingOutlined };
